spring.application.name=core

spring.r2dbc.url=r2dbc:h2:file:///~/db/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

# Database Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# Server Port
server.port=8085

# Logging for Debugging
logging.level.com.h2database=DEBUG
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

# Response Size Limit
spring.codec.max-in-memory-size=10MB

# Actuator Endpoints (optional)
management.endpoints.web.exposure.include=health,info,metrics

# JWT
jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLong123
jwt.expiration=86400000

##sdadsadsada